# Generated by Django 3.2.3 on 2021-06-01 21:09

import builder.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=70, unique=True, verbose_name='Email')),
                ('user_sid', models.CharField(default=builder.models.uid, editable=False, max_length=8, unique=True, verbose_name='UID')),
                ('user_cid', models.CharField(default=builder.models.cid, editable=False, max_length=8, unique=True, verbose_name='UCheckID')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date Joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Last Login')),
                ('is_pro', models.BooleanField(default=False, verbose_name='Pro User')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
