# Generated by Django 3.2.3 on 2021-06-02 14:51

import builder.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_resumetemplate_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumetemplate',
            name='resume_type',
            field=models.CharField(editable=False, max_length=15, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='resumetemplate',
            name='resume_uid',
            field=models.CharField(default=builder.models.ruid, editable=False, max_length=8, unique=True, verbose_name='R_UID'),
        ),
    ]
