# Generated by Django 3.2.3 on 2021-06-04 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0004_personaldetails_personcertification_personhobbies_personimage_personlang_personobjective_personposit'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_cid', models.CharField(max_length=10, verbose_name='CheckID')),
                ('lang', models.CharField(blank=True, max_length=255, null=True, verbose_name='Known Language')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='PersonLang',
        ),
    ]
