# Generated by Django 3.2.3 on 2021-06-06 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0005_auto_20210604_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='contact',
            field=models.BigIntegerField(verbose_name='Contact'),
        ),
    ]
