# Generated by Django 3.2.3 on 2021-06-06 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0008_auto_20210606_1127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personacademicqualification',
            old_name='user',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='personcareerobjective',
            old_name='user',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='personcertificationcourse',
            old_name='user',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='persondetail',
            old_name='user',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='personhobbie',
            old_name='user',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='personknownlanguage',
            old_name='user',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='personposition',
            old_name='user',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='personprofileimage',
            old_name='user',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='personproject',
            old_name='user',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='personskill',
            old_name='user',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='personworkexperience',
            old_name='user',
            new_name='person',
        ),
    ]
