# Generated by Django 3.2.3 on 2021-06-06 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0009_auto_20210606_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persondetail',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
